apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yme83s644-go 
  janus-idp.io/tekton: yme83s644-go
  backstage.io/kubernetes-id: yme83s644-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yme83s644-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  