apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yme83s644-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yme83s644-go 
  name: yme83s644-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: yme83s644-go 
